name: Code checking and unit tests
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  unit-tests-and-code-sniffer:
    name: "Pytest unit tests and code sniffer"
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        python-version: ['3.7.11']
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: '${{ matrix.python-version }}'
      - name: Install dependencies
        run: pipenv install --dev
      - name: Run unit tests and code sniffers
        run: |
          pycodestyle sws_py_sdk --config=./pycodestyle
          pipenv run python -m pytest tests/spec